package com.websharp.dwtz.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ENTITY_LOCATION.
 */
public class EntityLocation {

    public Integer ID;
    public String Name;
    public String TraName;
    public String EName;
    public Integer ParentID;
    public Integer LocationLevel;

    public EntityLocation() {
    }

    public EntityLocation(Integer ID, String Name, String TraName, String EName, Integer ParentID, Integer LocationLevel) {
        this.ID = ID;
        this.Name = Name;
        this.TraName = TraName;
        this.EName = EName;
        this.ParentID = ParentID;
        this.LocationLevel = LocationLevel;
    }

    public Integer getID() {
        return ID;
    }

    public void setID(Integer ID) {
        this.ID = ID;
    }

    public String getName() {
        return Name;
    }

    public void setName(String Name) {
        this.Name = Name;
    }

    public String getTraName() {
        return TraName;
    }

    public void setTraName(String TraName) {
        this.TraName = TraName;
    }

    public String getEName() {
        return EName;
    }

    public void setEName(String EName) {
        this.EName = EName;
    }

    public Integer getParentID() {
        return ParentID;
    }

    public void setParentID(Integer ParentID) {
        this.ParentID = ParentID;
    }

    public Integer getLocationLevel() {
        return LocationLevel;
    }

    public void setLocationLevel(Integer LocationLevel) {
        this.LocationLevel = LocationLevel;
    }

}
