package com.websharp.dwtz.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ENTITY_QUARANTINE.
 */
public class EntityQuarantine {

    public String InnerID;
    public String ButcheryID;
    public String DeliveryNum;
    public String SendTime;
    public String GoodsOwner;
    public String Origin;
    public String QuarantineNum;
    public String QuarantineCount;
    public String ActualCount;
    public String ImmuneTag;
    public String CheckCount;
    public String CheckNegativeCount;
    public String CheckPositiveCount;
    public String UnqualiedCount;
    public String QualiedCount;
    public String ProcessReason;
    public String ProcessComment;
    public String OfficalVeterSign;
    public String Remark;
    public String Add_UserID;
    public String Add_Time;
    public String Add_IP;
    public String Update_UserID;
    public String Update_Time;
    public String Update_IP;
    public String StaffNo;
    public String PicBatchID;
    public String origin_province_id;
    public String origin_city_id;
    public String origin_county_id;

    public EntityQuarantine() {
    }

    public EntityQuarantine(String InnerID, String ButcheryID, String DeliveryNum, String SendTime, String GoodsOwner, String Origin, String QuarantineNum, String QuarantineCount, String ActualCount, String ImmuneTag, String CheckCount, String CheckNegativeCount, String CheckPositiveCount, String UnqualiedCount, String QualiedCount, String ProcessReason, String ProcessComment, String OfficalVeterSign, String Remark, String Add_UserID, String Add_Time, String Add_IP, String Update_UserID, String Update_Time, String Update_IP, String StaffNo, String PicBatchID, String origin_province_id, String origin_city_id, String origin_county_id) {
        this.InnerID = InnerID;
        this.ButcheryID = ButcheryID;
        this.DeliveryNum = DeliveryNum;
        this.SendTime = SendTime;
        this.GoodsOwner = GoodsOwner;
        this.Origin = Origin;
        this.QuarantineNum = QuarantineNum;
        this.QuarantineCount = QuarantineCount;
        this.ActualCount = ActualCount;
        this.ImmuneTag = ImmuneTag;
        this.CheckCount = CheckCount;
        this.CheckNegativeCount = CheckNegativeCount;
        this.CheckPositiveCount = CheckPositiveCount;
        this.UnqualiedCount = UnqualiedCount;
        this.QualiedCount = QualiedCount;
        this.ProcessReason = ProcessReason;
        this.ProcessComment = ProcessComment;
        this.OfficalVeterSign = OfficalVeterSign;
        this.Remark = Remark;
        this.Add_UserID = Add_UserID;
        this.Add_Time = Add_Time;
        this.Add_IP = Add_IP;
        this.Update_UserID = Update_UserID;
        this.Update_Time = Update_Time;
        this.Update_IP = Update_IP;
        this.StaffNo = StaffNo;
        this.PicBatchID = PicBatchID;
        this.origin_province_id = origin_province_id;
        this.origin_city_id = origin_city_id;
        this.origin_county_id = origin_county_id;
    }

    public String getInnerID() {
        return InnerID;
    }

    public void setInnerID(String InnerID) {
        this.InnerID = InnerID;
    }

    public String getButcheryID() {
        return ButcheryID;
    }

    public void setButcheryID(String ButcheryID) {
        this.ButcheryID = ButcheryID;
    }

    public String getDeliveryNum() {
        return DeliveryNum;
    }

    public void setDeliveryNum(String DeliveryNum) {
        this.DeliveryNum = DeliveryNum;
    }

    public String getSendTime() {
        return SendTime;
    }

    public void setSendTime(String SendTime) {
        this.SendTime = SendTime;
    }

    public String getGoodsOwner() {
        return GoodsOwner;
    }

    public void setGoodsOwner(String GoodsOwner) {
        this.GoodsOwner = GoodsOwner;
    }

    public String getOrigin() {
        return Origin;
    }

    public void setOrigin(String Origin) {
        this.Origin = Origin;
    }

    public String getQuarantineNum() {
        return QuarantineNum;
    }

    public void setQuarantineNum(String QuarantineNum) {
        this.QuarantineNum = QuarantineNum;
    }

    public String getQuarantineCount() {
        return QuarantineCount;
    }

    public void setQuarantineCount(String QuarantineCount) {
        this.QuarantineCount = QuarantineCount;
    }

    public String getActualCount() {
        return ActualCount;
    }

    public void setActualCount(String ActualCount) {
        this.ActualCount = ActualCount;
    }

    public String getImmuneTag() {
        return ImmuneTag;
    }

    public void setImmuneTag(String ImmuneTag) {
        this.ImmuneTag = ImmuneTag;
    }

    public String getCheckCount() {
        return CheckCount;
    }

    public void setCheckCount(String CheckCount) {
        this.CheckCount = CheckCount;
    }

    public String getCheckNegativeCount() {
        return CheckNegativeCount;
    }

    public void setCheckNegativeCount(String CheckNegativeCount) {
        this.CheckNegativeCount = CheckNegativeCount;
    }

    public String getCheckPositiveCount() {
        return CheckPositiveCount;
    }

    public void setCheckPositiveCount(String CheckPositiveCount) {
        this.CheckPositiveCount = CheckPositiveCount;
    }

    public String getUnqualiedCount() {
        return UnqualiedCount;
    }

    public void setUnqualiedCount(String UnqualiedCount) {
        this.UnqualiedCount = UnqualiedCount;
    }

    public String getQualiedCount() {
        return QualiedCount;
    }

    public void setQualiedCount(String QualiedCount) {
        this.QualiedCount = QualiedCount;
    }

    public String getProcessReason() {
        return ProcessReason;
    }

    public void setProcessReason(String ProcessReason) {
        this.ProcessReason = ProcessReason;
    }

    public String getProcessComment() {
        return ProcessComment;
    }

    public void setProcessComment(String ProcessComment) {
        this.ProcessComment = ProcessComment;
    }

    public String getOfficalVeterSign() {
        return OfficalVeterSign;
    }

    public void setOfficalVeterSign(String OfficalVeterSign) {
        this.OfficalVeterSign = OfficalVeterSign;
    }

    public String getRemark() {
        return Remark;
    }

    public void setRemark(String Remark) {
        this.Remark = Remark;
    }

    public String getAdd_UserID() {
        return Add_UserID;
    }

    public void setAdd_UserID(String Add_UserID) {
        this.Add_UserID = Add_UserID;
    }

    public String getAdd_Time() {
        return Add_Time;
    }

    public void setAdd_Time(String Add_Time) {
        this.Add_Time = Add_Time;
    }

    public String getAdd_IP() {
        return Add_IP;
    }

    public void setAdd_IP(String Add_IP) {
        this.Add_IP = Add_IP;
    }

    public String getUpdate_UserID() {
        return Update_UserID;
    }

    public void setUpdate_UserID(String Update_UserID) {
        this.Update_UserID = Update_UserID;
    }

    public String getUpdate_Time() {
        return Update_Time;
    }

    public void setUpdate_Time(String Update_Time) {
        this.Update_Time = Update_Time;
    }

    public String getUpdate_IP() {
        return Update_IP;
    }

    public void setUpdate_IP(String Update_IP) {
        this.Update_IP = Update_IP;
    }

    public String getStaffNo() {
        return StaffNo;
    }

    public void setStaffNo(String StaffNo) {
        this.StaffNo = StaffNo;
    }

    public String getPicBatchID() {
        return PicBatchID;
    }

    public void setPicBatchID(String PicBatchID) {
        this.PicBatchID = PicBatchID;
    }

    public String getOrigin_province_id() {
        return origin_province_id;
    }

    public void setOrigin_province_id(String origin_province_id) {
        this.origin_province_id = origin_province_id;
    }

    public String getOrigin_city_id() {
        return origin_city_id;
    }

    public void setOrigin_city_id(String origin_city_id) {
        this.origin_city_id = origin_city_id;
    }

    public String getOrigin_county_id() {
        return origin_county_id;
    }

    public void setOrigin_county_id(String origin_county_id) {
        this.origin_county_id = origin_county_id;
    }

}
