package com.websharp.dwtz.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ENTITY_ARTICLE.
 */
public class EntityArticle {

    public String InnerID;
    public String Title;
    public String ArticleContent;
    public String CutPath;
    public String PublishTime;

    public EntityArticle() {
    }

    public EntityArticle(String InnerID, String Title, String ArticleContent, String CutPath, String PublishTime) {
        this.InnerID = InnerID;
        this.Title = Title;
        this.ArticleContent = ArticleContent;
        this.CutPath = CutPath;
        this.PublishTime = PublishTime;
    }

    public String getInnerID() {
        return InnerID;
    }

    public void setInnerID(String InnerID) {
        this.InnerID = InnerID;
    }

    public String getTitle() {
        return Title;
    }

    public void setTitle(String Title) {
        this.Title = Title;
    }

    public String getArticleContent() {
        return ArticleContent;
    }

    public void setArticleContent(String ArticleContent) {
        this.ArticleContent = ArticleContent;
    }

    public String getCutPath() {
        return CutPath;
    }

    public void setCutPath(String CutPath) {
        this.CutPath = CutPath;
    }

    public String getPublishTime() {
        return PublishTime;
    }

    public void setPublishTime(String PublishTime) {
        this.PublishTime = PublishTime;
    }

}
