package com.websharp.dwtz.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ENTITY_COMMON_DATA.
 */
public class EntityCommonData {

    public Integer InnerID;
    public String Type;
    public String ButcheryID;
    public String DataValue;
    public String Remark;
    public Integer Status;

    public EntityCommonData() {
    }

    public EntityCommonData(Integer InnerID, String Type, String ButcheryID, String DataValue, String Remark, Integer Status) {
        this.InnerID = InnerID;
        this.Type = Type;
        this.ButcheryID = ButcheryID;
        this.DataValue = DataValue;
        this.Remark = Remark;
        this.Status = Status;
    }

    public Integer getInnerID() {
        return InnerID;
    }

    public void setInnerID(Integer InnerID) {
        this.InnerID = InnerID;
    }

    public String getType() {
        return Type;
    }

    public void setType(String Type) {
        this.Type = Type;
    }

    public String getButcheryID() {
        return ButcheryID;
    }

    public void setButcheryID(String ButcheryID) {
        this.ButcheryID = ButcheryID;
    }

    public String getDataValue() {
        return DataValue;
    }

    public void setDataValue(String DataValue) {
        this.DataValue = DataValue;
    }

    public String getRemark() {
        return Remark;
    }

    public void setRemark(String Remark) {
        this.Remark = Remark;
    }

    public Integer getStatus() {
        return Status;
    }

    public void setStatus(Integer Status) {
        this.Status = Status;
    }

}
