package com.websharp.dwtz.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ENTITY_ANIMAL_SLAUGHTER_IMMUNE_APPLY.
 */
public class EntityAnimalSlaughterImmuneApply {

    public String innerid;
    public String apply_user_name;
    public String apply_time;
    public String inspection_staff;
    public String inspection_staff_telephone;
    public String animal_type;
    public String animal_count;
    public String animal_origin;
    public String entrance_immune_num;
    public String is_special_channel_in;
    public String clinic_health;
    public String is_animal_ear_tag;
    public String target_address;
    public String start_trans_time;
    public String is_read_warn;
    public String confirm_status;
    public String do_check_time;
    public String do_check_address;
    public String reject_reason;
    public String confirm_user_name;
    public String Add_UserID;
    public String Add_Time;
    public String Add_IP;
    public String Update_UserID;
    public String Update_Time;
    public String Update_IP;
    public String Inventory;
    public String InventoryStatus;
    public String SlaughterCapacity;
    public String butchery_id;
    public String signature_src;

    public EntityAnimalSlaughterImmuneApply() {
    }

    public EntityAnimalSlaughterImmuneApply(String innerid, String apply_user_name, String apply_time, String inspection_staff, String inspection_staff_telephone, String animal_type, String animal_count, String animal_origin, String entrance_immune_num, String is_special_channel_in, String clinic_health, String is_animal_ear_tag, String target_address, String start_trans_time, String is_read_warn, String confirm_status, String do_check_time, String do_check_address, String reject_reason, String confirm_user_name, String Add_UserID, String Add_Time, String Add_IP, String Update_UserID, String Update_Time, String Update_IP, String Inventory, String InventoryStatus, String SlaughterCapacity, String butchery_id, String signature_src) {
        this.innerid = innerid;
        this.apply_user_name = apply_user_name;
        this.apply_time = apply_time;
        this.inspection_staff = inspection_staff;
        this.inspection_staff_telephone = inspection_staff_telephone;
        this.animal_type = animal_type;
        this.animal_count = animal_count;
        this.animal_origin = animal_origin;
        this.entrance_immune_num = entrance_immune_num;
        this.is_special_channel_in = is_special_channel_in;
        this.clinic_health = clinic_health;
        this.is_animal_ear_tag = is_animal_ear_tag;
        this.target_address = target_address;
        this.start_trans_time = start_trans_time;
        this.is_read_warn = is_read_warn;
        this.confirm_status = confirm_status;
        this.do_check_time = do_check_time;
        this.do_check_address = do_check_address;
        this.reject_reason = reject_reason;
        this.confirm_user_name = confirm_user_name;
        this.Add_UserID = Add_UserID;
        this.Add_Time = Add_Time;
        this.Add_IP = Add_IP;
        this.Update_UserID = Update_UserID;
        this.Update_Time = Update_Time;
        this.Update_IP = Update_IP;
        this.Inventory = Inventory;
        this.InventoryStatus = InventoryStatus;
        this.SlaughterCapacity = SlaughterCapacity;
        this.butchery_id = butchery_id;
        this.signature_src = signature_src;
    }

    public String getInnerid() {
        return innerid;
    }

    public void setInnerid(String innerid) {
        this.innerid = innerid;
    }

    public String getApply_user_name() {
        return apply_user_name;
    }

    public void setApply_user_name(String apply_user_name) {
        this.apply_user_name = apply_user_name;
    }

    public String getApply_time() {
        return apply_time;
    }

    public void setApply_time(String apply_time) {
        this.apply_time = apply_time;
    }

    public String getInspection_staff() {
        return inspection_staff;
    }

    public void setInspection_staff(String inspection_staff) {
        this.inspection_staff = inspection_staff;
    }

    public String getInspection_staff_telephone() {
        return inspection_staff_telephone;
    }

    public void setInspection_staff_telephone(String inspection_staff_telephone) {
        this.inspection_staff_telephone = inspection_staff_telephone;
    }

    public String getAnimal_type() {
        return animal_type;
    }

    public void setAnimal_type(String animal_type) {
        this.animal_type = animal_type;
    }

    public String getAnimal_count() {
        return animal_count;
    }

    public void setAnimal_count(String animal_count) {
        this.animal_count = animal_count;
    }

    public String getAnimal_origin() {
        return animal_origin;
    }

    public void setAnimal_origin(String animal_origin) {
        this.animal_origin = animal_origin;
    }

    public String getEntrance_immune_num() {
        return entrance_immune_num;
    }

    public void setEntrance_immune_num(String entrance_immune_num) {
        this.entrance_immune_num = entrance_immune_num;
    }

    public String getIs_special_channel_in() {
        return is_special_channel_in;
    }

    public void setIs_special_channel_in(String is_special_channel_in) {
        this.is_special_channel_in = is_special_channel_in;
    }

    public String getClinic_health() {
        return clinic_health;
    }

    public void setClinic_health(String clinic_health) {
        this.clinic_health = clinic_health;
    }

    public String getIs_animal_ear_tag() {
        return is_animal_ear_tag;
    }

    public void setIs_animal_ear_tag(String is_animal_ear_tag) {
        this.is_animal_ear_tag = is_animal_ear_tag;
    }

    public String getTarget_address() {
        return target_address;
    }

    public void setTarget_address(String target_address) {
        this.target_address = target_address;
    }

    public String getStart_trans_time() {
        return start_trans_time;
    }

    public void setStart_trans_time(String start_trans_time) {
        this.start_trans_time = start_trans_time;
    }

    public String getIs_read_warn() {
        return is_read_warn;
    }

    public void setIs_read_warn(String is_read_warn) {
        this.is_read_warn = is_read_warn;
    }

    public String getConfirm_status() {
        return confirm_status;
    }

    public void setConfirm_status(String confirm_status) {
        this.confirm_status = confirm_status;
    }

    public String getDo_check_time() {
        return do_check_time;
    }

    public void setDo_check_time(String do_check_time) {
        this.do_check_time = do_check_time;
    }

    public String getDo_check_address() {
        return do_check_address;
    }

    public void setDo_check_address(String do_check_address) {
        this.do_check_address = do_check_address;
    }

    public String getReject_reason() {
        return reject_reason;
    }

    public void setReject_reason(String reject_reason) {
        this.reject_reason = reject_reason;
    }

    public String getConfirm_user_name() {
        return confirm_user_name;
    }

    public void setConfirm_user_name(String confirm_user_name) {
        this.confirm_user_name = confirm_user_name;
    }

    public String getAdd_UserID() {
        return Add_UserID;
    }

    public void setAdd_UserID(String Add_UserID) {
        this.Add_UserID = Add_UserID;
    }

    public String getAdd_Time() {
        return Add_Time;
    }

    public void setAdd_Time(String Add_Time) {
        this.Add_Time = Add_Time;
    }

    public String getAdd_IP() {
        return Add_IP;
    }

    public void setAdd_IP(String Add_IP) {
        this.Add_IP = Add_IP;
    }

    public String getUpdate_UserID() {
        return Update_UserID;
    }

    public void setUpdate_UserID(String Update_UserID) {
        this.Update_UserID = Update_UserID;
    }

    public String getUpdate_Time() {
        return Update_Time;
    }

    public void setUpdate_Time(String Update_Time) {
        this.Update_Time = Update_Time;
    }

    public String getUpdate_IP() {
        return Update_IP;
    }

    public void setUpdate_IP(String Update_IP) {
        this.Update_IP = Update_IP;
    }

    public String getInventory() {
        return Inventory;
    }

    public void setInventory(String Inventory) {
        this.Inventory = Inventory;
    }

    public String getInventoryStatus() {
        return InventoryStatus;
    }

    public void setInventoryStatus(String InventoryStatus) {
        this.InventoryStatus = InventoryStatus;
    }

    public String getSlaughterCapacity() {
        return SlaughterCapacity;
    }

    public void setSlaughterCapacity(String SlaughterCapacity) {
        this.SlaughterCapacity = SlaughterCapacity;
    }

    public String getButchery_id() {
        return butchery_id;
    }

    public void setButchery_id(String butchery_id) {
        this.butchery_id = butchery_id;
    }

    public String getSignature_src() {
        return signature_src;
    }

    public void setSignature_src(String signature_src) {
        this.signature_src = signature_src;
    }

}
