package com.websharp.dwtz.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ENTITY_MODULE.
 */
public class EntityModule {

    public String InnerID;
    public String DisplayName;

    public EntityModule() {
    }

    public EntityModule(String InnerID, String DisplayName) {
        this.InnerID = InnerID;
        this.DisplayName = DisplayName;
    }

    public String getInnerID() {
        return InnerID;
    }

    public void setInnerID(String InnerID) {
        this.InnerID = InnerID;
    }

    public String getDisplayName() {
        return DisplayName;
    }

    public void setDisplayName(String DisplayName) {
        this.DisplayName = DisplayName;
    }

}
