package com.websharp.dwtz.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ENTITY_VERSION.
 */
public class EntityVersion {

    public String InnerID;
    public String VersionName;
    public String VersionCode;
    public String DownloadUrl;
    public String UpdateContent;
    public String Enable;
    public String Add_UserID;
    public String Add_Time;
    public String Add_IP;
    public String Update_UserID;
    public String Update_Time;
    public String Update_IP;

    public EntityVersion() {
    }

    public EntityVersion(String InnerID, String VersionName, String VersionCode, String DownloadUrl, String UpdateContent, String Enable, String Add_UserID, String Add_Time, String Add_IP, String Update_UserID, String Update_Time, String Update_IP) {
        this.InnerID = InnerID;
        this.VersionName = VersionName;
        this.VersionCode = VersionCode;
        this.DownloadUrl = DownloadUrl;
        this.UpdateContent = UpdateContent;
        this.Enable = Enable;
        this.Add_UserID = Add_UserID;
        this.Add_Time = Add_Time;
        this.Add_IP = Add_IP;
        this.Update_UserID = Update_UserID;
        this.Update_Time = Update_Time;
        this.Update_IP = Update_IP;
    }

    public String getInnerID() {
        return InnerID;
    }

    public void setInnerID(String InnerID) {
        this.InnerID = InnerID;
    }

    public String getVersionName() {
        return VersionName;
    }

    public void setVersionName(String VersionName) {
        this.VersionName = VersionName;
    }

    public String getVersionCode() {
        return VersionCode;
    }

    public void setVersionCode(String VersionCode) {
        this.VersionCode = VersionCode;
    }

    public String getDownloadUrl() {
        return DownloadUrl;
    }

    public void setDownloadUrl(String DownloadUrl) {
        this.DownloadUrl = DownloadUrl;
    }

    public String getUpdateContent() {
        return UpdateContent;
    }

    public void setUpdateContent(String UpdateContent) {
        this.UpdateContent = UpdateContent;
    }

    public String getEnable() {
        return Enable;
    }

    public void setEnable(String Enable) {
        this.Enable = Enable;
    }

    public String getAdd_UserID() {
        return Add_UserID;
    }

    public void setAdd_UserID(String Add_UserID) {
        this.Add_UserID = Add_UserID;
    }

    public String getAdd_Time() {
        return Add_Time;
    }

    public void setAdd_Time(String Add_Time) {
        this.Add_Time = Add_Time;
    }

    public String getAdd_IP() {
        return Add_IP;
    }

    public void setAdd_IP(String Add_IP) {
        this.Add_IP = Add_IP;
    }

    public String getUpdate_UserID() {
        return Update_UserID;
    }

    public void setUpdate_UserID(String Update_UserID) {
        this.Update_UserID = Update_UserID;
    }

    public String getUpdate_Time() {
        return Update_Time;
    }

    public void setUpdate_Time(String Update_Time) {
        this.Update_Time = Update_Time;
    }

    public String getUpdate_IP() {
        return Update_IP;
    }

    public void setUpdate_IP(String Update_IP) {
        this.Update_IP = Update_IP;
    }

}
