package com.websharp.dwtz.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.websharp.dwtz.dao.EntityDestroy;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table ENTITY_DESTROY.
*/
public class EntityDestroyDao extends AbstractDao<EntityDestroy, Void> {

    public static final String TABLENAME = "ENTITY_DESTROY";

    /**
     * Properties of entity EntityDestroy.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property InnerID = new Property(0, String.class, "InnerID", false, "INNER_ID");
        public final static Property DestroyNum = new Property(1, String.class, "DestroyNum", false, "DESTROY_NUM");
        public final static Property Remark = new Property(2, String.class, "Remark", false, "REMARK");
        public final static Property Add_UserID = new Property(3, String.class, "Add_UserID", false, "ADD__USER_ID");
        public final static Property Add_Time = new Property(4, String.class, "Add_Time", false, "ADD__TIME");
        public final static Property Add_IP = new Property(5, String.class, "Add_IP", false, "ADD__IP");
        public final static Property Update_UserID = new Property(6, String.class, "Update_UserID", false, "UPDATE__USER_ID");
        public final static Property Update_Time = new Property(7, String.class, "Update_Time", false, "UPDATE__TIME");
        public final static Property Update_IP = new Property(8, String.class, "Update_IP", false, "UPDATE__IP");
        public final static Property ButcheryID = new Property(9, String.class, "ButcheryID", false, "BUTCHERY_ID");
        public final static Property Status = new Property(10, Integer.class, "Status", false, "STATUS");
        public final static Property TotalCount = new Property(11, Integer.class, "TotalCount", false, "TOTAL_COUNT");
    };


    public EntityDestroyDao(DaoConfig config) {
        super(config);
    }
    
    public EntityDestroyDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'ENTITY_DESTROY' (" + //
                "'INNER_ID' TEXT," + // 0: InnerID
                "'DESTROY_NUM' TEXT," + // 1: DestroyNum
                "'REMARK' TEXT," + // 2: Remark
                "'ADD__USER_ID' TEXT," + // 3: Add_UserID
                "'ADD__TIME' TEXT," + // 4: Add_Time
                "'ADD__IP' TEXT," + // 5: Add_IP
                "'UPDATE__USER_ID' TEXT," + // 6: Update_UserID
                "'UPDATE__TIME' TEXT," + // 7: Update_Time
                "'UPDATE__IP' TEXT," + // 8: Update_IP
                "'BUTCHERY_ID' TEXT," + // 9: ButcheryID
                "'STATUS' INTEGER," + // 10: Status
                "'TOTAL_COUNT' INTEGER);"); // 11: TotalCount
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'ENTITY_DESTROY'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, EntityDestroy entity) {
        stmt.clearBindings();
 
        String InnerID = entity.getInnerID();
        if (InnerID != null) {
            stmt.bindString(1, InnerID);
        }
 
        String DestroyNum = entity.getDestroyNum();
        if (DestroyNum != null) {
            stmt.bindString(2, DestroyNum);
        }
 
        String Remark = entity.getRemark();
        if (Remark != null) {
            stmt.bindString(3, Remark);
        }
 
        String Add_UserID = entity.getAdd_UserID();
        if (Add_UserID != null) {
            stmt.bindString(4, Add_UserID);
        }
 
        String Add_Time = entity.getAdd_Time();
        if (Add_Time != null) {
            stmt.bindString(5, Add_Time);
        }
 
        String Add_IP = entity.getAdd_IP();
        if (Add_IP != null) {
            stmt.bindString(6, Add_IP);
        }
 
        String Update_UserID = entity.getUpdate_UserID();
        if (Update_UserID != null) {
            stmt.bindString(7, Update_UserID);
        }
 
        String Update_Time = entity.getUpdate_Time();
        if (Update_Time != null) {
            stmt.bindString(8, Update_Time);
        }
 
        String Update_IP = entity.getUpdate_IP();
        if (Update_IP != null) {
            stmt.bindString(9, Update_IP);
        }
 
        String ButcheryID = entity.getButcheryID();
        if (ButcheryID != null) {
            stmt.bindString(10, ButcheryID);
        }
 
        Integer Status = entity.getStatus();
        if (Status != null) {
            stmt.bindLong(11, Status);
        }
 
        Integer TotalCount = entity.getTotalCount();
        if (TotalCount != null) {
            stmt.bindLong(12, TotalCount);
        }
    }

    /** @inheritdoc */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    /** @inheritdoc */
    @Override
    public EntityDestroy readEntity(Cursor cursor, int offset) {
        EntityDestroy entity = new EntityDestroy( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // InnerID
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // DestroyNum
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // Remark
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // Add_UserID
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // Add_Time
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // Add_IP
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // Update_UserID
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // Update_Time
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // Update_IP
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // ButcheryID
            cursor.isNull(offset + 10) ? null : cursor.getInt(offset + 10), // Status
            cursor.isNull(offset + 11) ? null : cursor.getInt(offset + 11) // TotalCount
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, EntityDestroy entity, int offset) {
        entity.setInnerID(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setDestroyNum(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setRemark(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setAdd_UserID(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setAdd_Time(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setAdd_IP(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setUpdate_UserID(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setUpdate_Time(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setUpdate_IP(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setButcheryID(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setStatus(cursor.isNull(offset + 10) ? null : cursor.getInt(offset + 10));
        entity.setTotalCount(cursor.isNull(offset + 11) ? null : cursor.getInt(offset + 11));
     }
    
    /** @inheritdoc */
    @Override
    protected Void updateKeyAfterInsert(EntityDestroy entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    /** @inheritdoc */
    @Override
    public Void getKey(EntityDestroy entity) {
        return null;
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
