package com.websharp.dwtz.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ENTITY_USER.
 */
public class EntityUser {

    public String Description;
    public String Email;
    public String InnerID;
    public String LastLogin;
    public String NavigationUrl;
    public String Password;
    public String Role;
    public String StaffNo;
    public String Telephone;
    public String UserID;
    public String UserName;
    public String ButcheryID;
    public String ApplyCompanyName;

    public EntityUser() {
    }

    public EntityUser(String Description, String Email, String InnerID, String LastLogin, String NavigationUrl, String Password, String Role, String StaffNo, String Telephone, String UserID, String UserName, String ButcheryID, String ApplyCompanyName) {
        this.Description = Description;
        this.Email = Email;
        this.InnerID = InnerID;
        this.LastLogin = LastLogin;
        this.NavigationUrl = NavigationUrl;
        this.Password = Password;
        this.Role = Role;
        this.StaffNo = StaffNo;
        this.Telephone = Telephone;
        this.UserID = UserID;
        this.UserName = UserName;
        this.ButcheryID = ButcheryID;
        this.ApplyCompanyName = ApplyCompanyName;
    }

    public String getDescription() {
        return Description;
    }

    public void setDescription(String Description) {
        this.Description = Description;
    }

    public String getEmail() {
        return Email;
    }

    public void setEmail(String Email) {
        this.Email = Email;
    }

    public String getInnerID() {
        return InnerID;
    }

    public void setInnerID(String InnerID) {
        this.InnerID = InnerID;
    }

    public String getLastLogin() {
        return LastLogin;
    }

    public void setLastLogin(String LastLogin) {
        this.LastLogin = LastLogin;
    }

    public String getNavigationUrl() {
        return NavigationUrl;
    }

    public void setNavigationUrl(String NavigationUrl) {
        this.NavigationUrl = NavigationUrl;
    }

    public String getPassword() {
        return Password;
    }

    public void setPassword(String Password) {
        this.Password = Password;
    }

    public String getRole() {
        return Role;
    }

    public void setRole(String Role) {
        this.Role = Role;
    }

    public String getStaffNo() {
        return StaffNo;
    }

    public void setStaffNo(String StaffNo) {
        this.StaffNo = StaffNo;
    }

    public String getTelephone() {
        return Telephone;
    }

    public void setTelephone(String Telephone) {
        this.Telephone = Telephone;
    }

    public String getUserID() {
        return UserID;
    }

    public void setUserID(String UserID) {
        this.UserID = UserID;
    }

    public String getUserName() {
        return UserName;
    }

    public void setUserName(String UserName) {
        this.UserName = UserName;
    }

    public String getButcheryID() {
        return ButcheryID;
    }

    public void setButcheryID(String ButcheryID) {
        this.ButcheryID = ButcheryID;
    }

    public String getApplyCompanyName() {
        return ApplyCompanyName;
    }

    public void setApplyCompanyName(String ApplyCompanyName) {
        this.ApplyCompanyName = ApplyCompanyName;
    }

}
