package com.websharp.dwtz.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ENTITY_UNQUALIED.
 */
public class EntityUnqualied {

    public String InnerID;
    public String QuarantineId;
    public String UnqualiedScanCode;
    public String UnqualiedScanCode_2;
    public String ButcheryID;
    public String DeliveryNum;
    public String SendTime;
    public String GoodsOwner;
    public String Origin;
    public String QuarantineNum;
    public String ImmuneTag;
    public String CheckCount;
    public String ProcessReason;
    public String ProcessComment;
    public String OfficalVeterSign;
    public String Remark;
    public String Add_UserID;
    public String Add_Time;
    public String StaffNo;
    public String ButcheryGroupID;
    public String Weight;
    public String Type;

    public EntityUnqualied() {
    }

    public EntityUnqualied(String InnerID, String QuarantineId, String UnqualiedScanCode, String UnqualiedScanCode_2, String ButcheryID, String DeliveryNum, String SendTime, String GoodsOwner, String Origin, String QuarantineNum, String ImmuneTag, String CheckCount, String ProcessReason, String ProcessComment, String OfficalVeterSign, String Remark, String Add_UserID, String Add_Time, String StaffNo, String ButcheryGroupID, String Weight, String Type) {
        this.InnerID = InnerID;
        this.QuarantineId = QuarantineId;
        this.UnqualiedScanCode = UnqualiedScanCode;
        this.UnqualiedScanCode_2 = UnqualiedScanCode_2;
        this.ButcheryID = ButcheryID;
        this.DeliveryNum = DeliveryNum;
        this.SendTime = SendTime;
        this.GoodsOwner = GoodsOwner;
        this.Origin = Origin;
        this.QuarantineNum = QuarantineNum;
        this.ImmuneTag = ImmuneTag;
        this.CheckCount = CheckCount;
        this.ProcessReason = ProcessReason;
        this.ProcessComment = ProcessComment;
        this.OfficalVeterSign = OfficalVeterSign;
        this.Remark = Remark;
        this.Add_UserID = Add_UserID;
        this.Add_Time = Add_Time;
        this.StaffNo = StaffNo;
        this.ButcheryGroupID = ButcheryGroupID;
        this.Weight = Weight;
        this.Type = Type;
    }

    public String getInnerID() {
        return InnerID;
    }

    public void setInnerID(String InnerID) {
        this.InnerID = InnerID;
    }

    public String getQuarantineId() {
        return QuarantineId;
    }

    public void setQuarantineId(String QuarantineId) {
        this.QuarantineId = QuarantineId;
    }

    public String getUnqualiedScanCode() {
        return UnqualiedScanCode;
    }

    public void setUnqualiedScanCode(String UnqualiedScanCode) {
        this.UnqualiedScanCode = UnqualiedScanCode;
    }

    public String getUnqualiedScanCode_2() {
        return UnqualiedScanCode_2;
    }

    public void setUnqualiedScanCode_2(String UnqualiedScanCode_2) {
        this.UnqualiedScanCode_2 = UnqualiedScanCode_2;
    }

    public String getButcheryID() {
        return ButcheryID;
    }

    public void setButcheryID(String ButcheryID) {
        this.ButcheryID = ButcheryID;
    }

    public String getDeliveryNum() {
        return DeliveryNum;
    }

    public void setDeliveryNum(String DeliveryNum) {
        this.DeliveryNum = DeliveryNum;
    }

    public String getSendTime() {
        return SendTime;
    }

    public void setSendTime(String SendTime) {
        this.SendTime = SendTime;
    }

    public String getGoodsOwner() {
        return GoodsOwner;
    }

    public void setGoodsOwner(String GoodsOwner) {
        this.GoodsOwner = GoodsOwner;
    }

    public String getOrigin() {
        return Origin;
    }

    public void setOrigin(String Origin) {
        this.Origin = Origin;
    }

    public String getQuarantineNum() {
        return QuarantineNum;
    }

    public void setQuarantineNum(String QuarantineNum) {
        this.QuarantineNum = QuarantineNum;
    }

    public String getImmuneTag() {
        return ImmuneTag;
    }

    public void setImmuneTag(String ImmuneTag) {
        this.ImmuneTag = ImmuneTag;
    }

    public String getCheckCount() {
        return CheckCount;
    }

    public void setCheckCount(String CheckCount) {
        this.CheckCount = CheckCount;
    }

    public String getProcessReason() {
        return ProcessReason;
    }

    public void setProcessReason(String ProcessReason) {
        this.ProcessReason = ProcessReason;
    }

    public String getProcessComment() {
        return ProcessComment;
    }

    public void setProcessComment(String ProcessComment) {
        this.ProcessComment = ProcessComment;
    }

    public String getOfficalVeterSign() {
        return OfficalVeterSign;
    }

    public void setOfficalVeterSign(String OfficalVeterSign) {
        this.OfficalVeterSign = OfficalVeterSign;
    }

    public String getRemark() {
        return Remark;
    }

    public void setRemark(String Remark) {
        this.Remark = Remark;
    }

    public String getAdd_UserID() {
        return Add_UserID;
    }

    public void setAdd_UserID(String Add_UserID) {
        this.Add_UserID = Add_UserID;
    }

    public String getAdd_Time() {
        return Add_Time;
    }

    public void setAdd_Time(String Add_Time) {
        this.Add_Time = Add_Time;
    }

    public String getStaffNo() {
        return StaffNo;
    }

    public void setStaffNo(String StaffNo) {
        this.StaffNo = StaffNo;
    }

    public String getButcheryGroupID() {
        return ButcheryGroupID;
    }

    public void setButcheryGroupID(String ButcheryGroupID) {
        this.ButcheryGroupID = ButcheryGroupID;
    }

    public String getWeight() {
        return Weight;
    }

    public void setWeight(String Weight) {
        this.Weight = Weight;
    }

    public String getType() {
        return Type;
    }

    public void setType(String Type) {
        this.Type = Type;
    }

}
