package com.websharp.dwtz.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.websharp.dwtz.dao.EntityDistributionApplyTarget;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table ENTITY_DISTRIBUTION_APPLY_TARGET.
*/
public class EntityDistributionApplyTargetDao extends AbstractDao<EntityDistributionApplyTarget, Void> {

    public static final String TABLENAME = "ENTITY_DISTRIBUTION_APPLY_TARGET";

    /**
     * Properties of entity EntityDistributionApplyTarget.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property InnerID = new Property(0, Integer.class, "InnerID", false, "INNER_ID");
        public final static Property Distribution_Apply_ID = new Property(1, String.class, "Distribution_Apply_ID", false, "DISTRIBUTION__APPLY__ID");
        public final static Property Distribution_Target_Address = new Property(2, String.class, "Distribution_Target_Address", false, "DISTRIBUTION__TARGET__ADDRESS");
        public final static Property Distribution_Count = new Property(3, Double.class, "Distribution_Count", false, "DISTRIBUTION__COUNT");
        public final static Property Apply_User_ID = new Property(4, String.class, "Apply_User_ID", false, "APPLY__USER__ID");
        public final static Property Add_UserID = new Property(5, String.class, "Add_UserID", false, "ADD__USER_ID");
        public final static Property Add_Time = new Property(6, String.class, "Add_Time", false, "ADD__TIME");
        public final static Property Add_IP = new Property(7, String.class, "Add_IP", false, "ADD__IP");
        public final static Property Update_UserID = new Property(8, String.class, "Update_UserID", false, "UPDATE__USER_ID");
        public final static Property Update_Time = new Property(9, String.class, "Update_Time", false, "UPDATE__TIME");
        public final static Property Update_IP = new Property(10, String.class, "Update_IP", false, "UPDATE__IP");
    };


    public EntityDistributionApplyTargetDao(DaoConfig config) {
        super(config);
    }
    
    public EntityDistributionApplyTargetDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'ENTITY_DISTRIBUTION_APPLY_TARGET' (" + //
                "'INNER_ID' INTEGER," + // 0: InnerID
                "'DISTRIBUTION__APPLY__ID' TEXT," + // 1: Distribution_Apply_ID
                "'DISTRIBUTION__TARGET__ADDRESS' TEXT," + // 2: Distribution_Target_Address
                "'DISTRIBUTION__COUNT' REAL," + // 3: Distribution_Count
                "'APPLY__USER__ID' TEXT," + // 4: Apply_User_ID
                "'ADD__USER_ID' TEXT," + // 5: Add_UserID
                "'ADD__TIME' TEXT," + // 6: Add_Time
                "'ADD__IP' TEXT," + // 7: Add_IP
                "'UPDATE__USER_ID' TEXT," + // 8: Update_UserID
                "'UPDATE__TIME' TEXT," + // 9: Update_Time
                "'UPDATE__IP' TEXT);"); // 10: Update_IP
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'ENTITY_DISTRIBUTION_APPLY_TARGET'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, EntityDistributionApplyTarget entity) {
        stmt.clearBindings();
 
        Integer InnerID = entity.getInnerID();
        if (InnerID != null) {
            stmt.bindLong(1, InnerID);
        }
 
        String Distribution_Apply_ID = entity.getDistribution_Apply_ID();
        if (Distribution_Apply_ID != null) {
            stmt.bindString(2, Distribution_Apply_ID);
        }
 
        String Distribution_Target_Address = entity.getDistribution_Target_Address();
        if (Distribution_Target_Address != null) {
            stmt.bindString(3, Distribution_Target_Address);
        }
 
        Double Distribution_Count = entity.getDistribution_Count();
        if (Distribution_Count != null) {
            stmt.bindDouble(4, Distribution_Count);
        }
 
        String Apply_User_ID = entity.getApply_User_ID();
        if (Apply_User_ID != null) {
            stmt.bindString(5, Apply_User_ID);
        }
 
        String Add_UserID = entity.getAdd_UserID();
        if (Add_UserID != null) {
            stmt.bindString(6, Add_UserID);
        }
 
        String Add_Time = entity.getAdd_Time();
        if (Add_Time != null) {
            stmt.bindString(7, Add_Time);
        }
 
        String Add_IP = entity.getAdd_IP();
        if (Add_IP != null) {
            stmt.bindString(8, Add_IP);
        }
 
        String Update_UserID = entity.getUpdate_UserID();
        if (Update_UserID != null) {
            stmt.bindString(9, Update_UserID);
        }
 
        String Update_Time = entity.getUpdate_Time();
        if (Update_Time != null) {
            stmt.bindString(10, Update_Time);
        }
 
        String Update_IP = entity.getUpdate_IP();
        if (Update_IP != null) {
            stmt.bindString(11, Update_IP);
        }
    }

    /** @inheritdoc */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    /** @inheritdoc */
    @Override
    public EntityDistributionApplyTarget readEntity(Cursor cursor, int offset) {
        EntityDistributionApplyTarget entity = new EntityDistributionApplyTarget( //
            cursor.isNull(offset + 0) ? null : cursor.getInt(offset + 0), // InnerID
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // Distribution_Apply_ID
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // Distribution_Target_Address
            cursor.isNull(offset + 3) ? null : cursor.getDouble(offset + 3), // Distribution_Count
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // Apply_User_ID
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // Add_UserID
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // Add_Time
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // Add_IP
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // Update_UserID
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // Update_Time
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10) // Update_IP
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, EntityDistributionApplyTarget entity, int offset) {
        entity.setInnerID(cursor.isNull(offset + 0) ? null : cursor.getInt(offset + 0));
        entity.setDistribution_Apply_ID(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDistribution_Target_Address(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setDistribution_Count(cursor.isNull(offset + 3) ? null : cursor.getDouble(offset + 3));
        entity.setApply_User_ID(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setAdd_UserID(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setAdd_Time(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setAdd_IP(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setUpdate_UserID(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setUpdate_Time(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setUpdate_IP(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
     }
    
    /** @inheritdoc */
    @Override
    protected Void updateKeyAfterInsert(EntityDistributionApplyTarget entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    /** @inheritdoc */
    @Override
    public Void getKey(EntityDistributionApplyTarget entity) {
        return null;
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
