package com.websharp.dwtz.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ENTITY_DISTRIBUTION_APPLY_TARGET.
 */
public class EntityDistributionApplyTarget {

    public Integer InnerID;
    public String Distribution_Apply_ID;
    public String Distribution_Target_Address;
    public Double Distribution_Count;
    public String Apply_User_ID;
    public String Add_UserID;
    public String Add_Time;
    public String Add_IP;
    public String Update_UserID;
    public String Update_Time;
    public String Update_IP;

    public EntityDistributionApplyTarget() {
    }

    public EntityDistributionApplyTarget(Integer InnerID, String Distribution_Apply_ID, String Distribution_Target_Address, Double Distribution_Count, String Apply_User_ID, String Add_UserID, String Add_Time, String Add_IP, String Update_UserID, String Update_Time, String Update_IP) {
        this.InnerID = InnerID;
        this.Distribution_Apply_ID = Distribution_Apply_ID;
        this.Distribution_Target_Address = Distribution_Target_Address;
        this.Distribution_Count = Distribution_Count;
        this.Apply_User_ID = Apply_User_ID;
        this.Add_UserID = Add_UserID;
        this.Add_Time = Add_Time;
        this.Add_IP = Add_IP;
        this.Update_UserID = Update_UserID;
        this.Update_Time = Update_Time;
        this.Update_IP = Update_IP;
    }

    public Integer getInnerID() {
        return InnerID;
    }

    public void setInnerID(Integer InnerID) {
        this.InnerID = InnerID;
    }

    public String getDistribution_Apply_ID() {
        return Distribution_Apply_ID;
    }

    public void setDistribution_Apply_ID(String Distribution_Apply_ID) {
        this.Distribution_Apply_ID = Distribution_Apply_ID;
    }

    public String getDistribution_Target_Address() {
        return Distribution_Target_Address;
    }

    public void setDistribution_Target_Address(String Distribution_Target_Address) {
        this.Distribution_Target_Address = Distribution_Target_Address;
    }

    public Double getDistribution_Count() {
        return Distribution_Count;
    }

    public void setDistribution_Count(Double Distribution_Count) {
        this.Distribution_Count = Distribution_Count;
    }

    public String getApply_User_ID() {
        return Apply_User_ID;
    }

    public void setApply_User_ID(String Apply_User_ID) {
        this.Apply_User_ID = Apply_User_ID;
    }

    public String getAdd_UserID() {
        return Add_UserID;
    }

    public void setAdd_UserID(String Add_UserID) {
        this.Add_UserID = Add_UserID;
    }

    public String getAdd_Time() {
        return Add_Time;
    }

    public void setAdd_Time(String Add_Time) {
        this.Add_Time = Add_Time;
    }

    public String getAdd_IP() {
        return Add_IP;
    }

    public void setAdd_IP(String Add_IP) {
        this.Add_IP = Add_IP;
    }

    public String getUpdate_UserID() {
        return Update_UserID;
    }

    public void setUpdate_UserID(String Update_UserID) {
        this.Update_UserID = Update_UserID;
    }

    public String getUpdate_Time() {
        return Update_Time;
    }

    public void setUpdate_Time(String Update_Time) {
        this.Update_Time = Update_Time;
    }

    public String getUpdate_IP() {
        return Update_IP;
    }

    public void setUpdate_IP(String Update_IP) {
        this.Update_IP = Update_IP;
    }

}
