package com.websharp.dwtz.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ENTITY_SLAUGHTER.
 */
public class EntitySlaughter {

    public String innerid;
    public String quarantine_id;
    public Integer qualied_count;
    public Integer unqualied_count;
    public String slaughter_time;
    public String whereabouts;
    public String immune_num;
    public String Add_UserID;
    public String Add_Time;
    public String Add_IP;
    public String Update_UserID;
    public String Update_Time;
    public String Update_IP;
    public String butchery_id;
    public String actual_kill_count;
    public String rest_count;
    public String is_rest_count_merge;
    public String apply_user_name;

    public EntitySlaughter() {
    }

    public EntitySlaughter(String innerid, String quarantine_id, Integer qualied_count, Integer unqualied_count, String slaughter_time, String whereabouts, String immune_num, String Add_UserID, String Add_Time, String Add_IP, String Update_UserID, String Update_Time, String Update_IP, String butchery_id, String actual_kill_count, String rest_count, String is_rest_count_merge, String apply_user_name) {
        this.innerid = innerid;
        this.quarantine_id = quarantine_id;
        this.qualied_count = qualied_count;
        this.unqualied_count = unqualied_count;
        this.slaughter_time = slaughter_time;
        this.whereabouts = whereabouts;
        this.immune_num = immune_num;
        this.Add_UserID = Add_UserID;
        this.Add_Time = Add_Time;
        this.Add_IP = Add_IP;
        this.Update_UserID = Update_UserID;
        this.Update_Time = Update_Time;
        this.Update_IP = Update_IP;
        this.butchery_id = butchery_id;
        this.actual_kill_count = actual_kill_count;
        this.rest_count = rest_count;
        this.is_rest_count_merge = is_rest_count_merge;
        this.apply_user_name = apply_user_name;
    }

    public String getInnerid() {
        return innerid;
    }

    public void setInnerid(String innerid) {
        this.innerid = innerid;
    }

    public String getQuarantine_id() {
        return quarantine_id;
    }

    public void setQuarantine_id(String quarantine_id) {
        this.quarantine_id = quarantine_id;
    }

    public Integer getQualied_count() {
        return qualied_count;
    }

    public void setQualied_count(Integer qualied_count) {
        this.qualied_count = qualied_count;
    }

    public Integer getUnqualied_count() {
        return unqualied_count;
    }

    public void setUnqualied_count(Integer unqualied_count) {
        this.unqualied_count = unqualied_count;
    }

    public String getSlaughter_time() {
        return slaughter_time;
    }

    public void setSlaughter_time(String slaughter_time) {
        this.slaughter_time = slaughter_time;
    }

    public String getWhereabouts() {
        return whereabouts;
    }

    public void setWhereabouts(String whereabouts) {
        this.whereabouts = whereabouts;
    }

    public String getImmune_num() {
        return immune_num;
    }

    public void setImmune_num(String immune_num) {
        this.immune_num = immune_num;
    }

    public String getAdd_UserID() {
        return Add_UserID;
    }

    public void setAdd_UserID(String Add_UserID) {
        this.Add_UserID = Add_UserID;
    }

    public String getAdd_Time() {
        return Add_Time;
    }

    public void setAdd_Time(String Add_Time) {
        this.Add_Time = Add_Time;
    }

    public String getAdd_IP() {
        return Add_IP;
    }

    public void setAdd_IP(String Add_IP) {
        this.Add_IP = Add_IP;
    }

    public String getUpdate_UserID() {
        return Update_UserID;
    }

    public void setUpdate_UserID(String Update_UserID) {
        this.Update_UserID = Update_UserID;
    }

    public String getUpdate_Time() {
        return Update_Time;
    }

    public void setUpdate_Time(String Update_Time) {
        this.Update_Time = Update_Time;
    }

    public String getUpdate_IP() {
        return Update_IP;
    }

    public void setUpdate_IP(String Update_IP) {
        this.Update_IP = Update_IP;
    }

    public String getButchery_id() {
        return butchery_id;
    }

    public void setButchery_id(String butchery_id) {
        this.butchery_id = butchery_id;
    }

    public String getActual_kill_count() {
        return actual_kill_count;
    }

    public void setActual_kill_count(String actual_kill_count) {
        this.actual_kill_count = actual_kill_count;
    }

    public String getRest_count() {
        return rest_count;
    }

    public void setRest_count(String rest_count) {
        this.rest_count = rest_count;
    }

    public String getIs_rest_count_merge() {
        return is_rest_count_merge;
    }

    public void setIs_rest_count_merge(String is_rest_count_merge) {
        this.is_rest_count_merge = is_rest_count_merge;
    }

    public String getApply_user_name() {
        return apply_user_name;
    }

    public void setApply_user_name(String apply_user_name) {
        this.apply_user_name = apply_user_name;
    }

}
