package com.websharp.dwtz.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.websharp.dwtz.dao.EntityButcheryGroup;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table ENTITY_BUTCHERY_GROUP.
*/
public class EntityButcheryGroupDao extends AbstractDao<EntityButcheryGroup, Void> {

    public static final String TABLENAME = "ENTITY_BUTCHERY_GROUP";

    /**
     * Properties of entity EntityButcheryGroup.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property InnerID = new Property(0, String.class, "InnerID", false, "INNER_ID");
        public final static Property ButcheryID = new Property(1, String.class, "ButcheryID", false, "BUTCHERY_ID");
        public final static Property GroupName = new Property(2, String.class, "GroupName", false, "GROUP_NAME");
        public final static Property GroupNo = new Property(3, String.class, "GroupNo", false, "GROUP_NO");
        public final static Property ButcheryName = new Property(4, String.class, "ButcheryName", false, "BUTCHERY_NAME");
        public final static Property Address = new Property(5, String.class, "Address", false, "ADDRESS");
        public final static Property Telephone = new Property(6, String.class, "Telephone", false, "TELEPHONE");
        public final static Property Master = new Property(7, String.class, "Master", false, "MASTER");
        public final static Property MasterTelephone = new Property(8, String.class, "MasterTelephone", false, "MASTER_TELEPHONE");
    };


    public EntityButcheryGroupDao(DaoConfig config) {
        super(config);
    }
    
    public EntityButcheryGroupDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'ENTITY_BUTCHERY_GROUP' (" + //
                "'INNER_ID' TEXT," + // 0: InnerID
                "'BUTCHERY_ID' TEXT," + // 1: ButcheryID
                "'GROUP_NAME' TEXT," + // 2: GroupName
                "'GROUP_NO' TEXT," + // 3: GroupNo
                "'BUTCHERY_NAME' TEXT," + // 4: ButcheryName
                "'ADDRESS' TEXT," + // 5: Address
                "'TELEPHONE' TEXT," + // 6: Telephone
                "'MASTER' TEXT," + // 7: Master
                "'MASTER_TELEPHONE' TEXT);"); // 8: MasterTelephone
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'ENTITY_BUTCHERY_GROUP'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, EntityButcheryGroup entity) {
        stmt.clearBindings();
 
        String InnerID = entity.getInnerID();
        if (InnerID != null) {
            stmt.bindString(1, InnerID);
        }
 
        String ButcheryID = entity.getButcheryID();
        if (ButcheryID != null) {
            stmt.bindString(2, ButcheryID);
        }
 
        String GroupName = entity.getGroupName();
        if (GroupName != null) {
            stmt.bindString(3, GroupName);
        }
 
        String GroupNo = entity.getGroupNo();
        if (GroupNo != null) {
            stmt.bindString(4, GroupNo);
        }
 
        String ButcheryName = entity.getButcheryName();
        if (ButcheryName != null) {
            stmt.bindString(5, ButcheryName);
        }
 
        String Address = entity.getAddress();
        if (Address != null) {
            stmt.bindString(6, Address);
        }
 
        String Telephone = entity.getTelephone();
        if (Telephone != null) {
            stmt.bindString(7, Telephone);
        }
 
        String Master = entity.getMaster();
        if (Master != null) {
            stmt.bindString(8, Master);
        }
 
        String MasterTelephone = entity.getMasterTelephone();
        if (MasterTelephone != null) {
            stmt.bindString(9, MasterTelephone);
        }
    }

    /** @inheritdoc */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    /** @inheritdoc */
    @Override
    public EntityButcheryGroup readEntity(Cursor cursor, int offset) {
        EntityButcheryGroup entity = new EntityButcheryGroup( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // InnerID
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // ButcheryID
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // GroupName
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // GroupNo
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // ButcheryName
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // Address
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // Telephone
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // Master
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8) // MasterTelephone
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, EntityButcheryGroup entity, int offset) {
        entity.setInnerID(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setButcheryID(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setGroupName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setGroupNo(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setButcheryName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setAddress(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setTelephone(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setMaster(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setMasterTelephone(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
     }
    
    /** @inheritdoc */
    @Override
    protected Void updateKeyAfterInsert(EntityButcheryGroup entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    /** @inheritdoc */
    @Override
    public Void getKey(EntityButcheryGroup entity) {
        return null;
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
