package com.websharp.dwtz.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ENTITY_BUTCHERY_GROUP.
 */
public class EntityButcheryGroup {

    public String InnerID;
    public String ButcheryID;
    public String GroupName;
    public String GroupNo;
    public String ButcheryName;
    public String Address;
    public String Telephone;
    public String Master;
    public String MasterTelephone;

    public EntityButcheryGroup() {
    }

    public EntityButcheryGroup(String InnerID, String ButcheryID, String GroupName, String GroupNo, String ButcheryName, String Address, String Telephone, String Master, String MasterTelephone) {
        this.InnerID = InnerID;
        this.ButcheryID = ButcheryID;
        this.GroupName = GroupName;
        this.GroupNo = GroupNo;
        this.ButcheryName = ButcheryName;
        this.Address = Address;
        this.Telephone = Telephone;
        this.Master = Master;
        this.MasterTelephone = MasterTelephone;
    }

    public String getInnerID() {
        return InnerID;
    }

    public void setInnerID(String InnerID) {
        this.InnerID = InnerID;
    }

    public String getButcheryID() {
        return ButcheryID;
    }

    public void setButcheryID(String ButcheryID) {
        this.ButcheryID = ButcheryID;
    }

    public String getGroupName() {
        return GroupName;
    }

    public void setGroupName(String GroupName) {
        this.GroupName = GroupName;
    }

    public String getGroupNo() {
        return GroupNo;
    }

    public void setGroupNo(String GroupNo) {
        this.GroupNo = GroupNo;
    }

    public String getButcheryName() {
        return ButcheryName;
    }

    public void setButcheryName(String ButcheryName) {
        this.ButcheryName = ButcheryName;
    }

    public String getAddress() {
        return Address;
    }

    public void setAddress(String Address) {
        this.Address = Address;
    }

    public String getTelephone() {
        return Telephone;
    }

    public void setTelephone(String Telephone) {
        this.Telephone = Telephone;
    }

    public String getMaster() {
        return Master;
    }

    public void setMaster(String Master) {
        this.Master = Master;
    }

    public String getMasterTelephone() {
        return MasterTelephone;
    }

    public void setMasterTelephone(String MasterTelephone) {
        this.MasterTelephone = MasterTelephone;
    }

}
